services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"
    env_file:
      - path: '.env'
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  postgres:
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - path: '.env'
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    env_file:
      - path: '.env'

volumes:
  rabbitmq_data:
