services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    env_file:
      - path: '.env'
    ports:
      - 15672:15672
      - 5672:5672
  postgres:
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - path: '.env'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    env_file:
      - path: '.env'
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data:
